### ISSUE TITLE
CLI bulk uploaded ended up with some photos having the wrong date - need to bulk delete 

### ISSUE THREAD

**Issue by RickyHaase** [immich-app/CLI#67]
### Issue:
I bulk exported from the Apple photos app "as originals" and then used the CLI to upload into my Immich Admin account. Alot of the images ended up with the wrong date and lots of photos are out of order.

### Workaround:
I made another account and tested bulk backing up from the mobile app. It was much slower (wifi, downloading from iCloud, etc.) but everything uploaded correctly and is all organized appropriately with the right dates (I did have a bug where a few dozen photos were missing after the backup was complete but a reinstall of the app caught those and everything is great now. I can open an issue for that in another repo if desired).

### Need Help:
Is there a way to bulk remove the photos that I added to the admin account? I can't "select all" or "shift click" in Immich to bulk delete. As expected, deleting from the file system just results in missing files but all the DB entries and thumbnails are still there (so I restored the files as to not cause issues). Are there a couple of commands I could use in one of the containers to drop all assets from a user and then manually delete all files? Or is there another already built way to do this?

**Comment by alextran1502** [comment]
Currently, there is no UI mechanism to do that, we would have to perform that task in the database.

A few questions:

`I bulk exported from the Apple photos app "as originals"`

Is this Apple photos app on MacOS?

`A lot of the images ended up with the wrong date, and lots of photos are out of order.`

Can you help double-check the metadata of the images and the information on the timeline? Technically the way that you are describing vs using the mobile app to backup shouldn't cause the different in the date because the date is processing in the server anyway.

**Comment by RickyHaase** [comment]
Okay so I looked in a little closer (sorry for not including this in the original post, it just didn't register with me at the time) and it looks like it's primarily all of the live photo clips. They say "no exif data" and for whatever reason, all ended up being put as "Feb 4, 2021" in Immich. There are also a number of shots scattered in there (appear to have come from sources like screenshots, SMS, or Snapchat), but I think you're spot on with it likely being an issue with the source metadata and not the Immich CLI.

And yes, the export was from Apple Photos on MacOS.

So I guess that covers the "issue" but would you be able to point me in the right direction as to how I need to bulk remove using the DB? Or is there another thread outlining that which I have missed?
